version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "YortziteApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mg3ooy6uphe7"
s3_prefix = "YortziteApp"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
